// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgeogyvjcbpemkvalgcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZW9neXZqY2JwZW1rdmFsZ2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDE0NjksImV4cCI6MjA1ODU3NzQ2OX0.Wf7i4ZMUnVa5S2ZxRPkwII9iV_m1CErFYrgO_Up-KuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);